global:
  slack_api_url: '<Slack''s Incoming Webhook URL>'
route:
  receiver: 'main_receiver'
  routes:
    - receiver: 'urgent_receiver'
      matchers:
        - severity="Critical"
receivers:
  - name: 'main_receiver'
    slack_configs:
      - channel: '#learn-grafana' 
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
  - name: 'urgent_receiver'
    slack_configs:
      - channel: '#learn-grafana-urgent-alerts' 
        send_resolved: true
        title: 'Urgent: Critical Alert - {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
