multitenancy_enabled: false

server:
  http_listen_port: 9009
  #grpc_listen_port: 9095

common:
  storage:
    backend: s3
    s3:
      bucket_name: your-mimir-bucket
      endpoint: s3.amazonaws.com # Use a specific endpoint if using non-default region or custom S3 provider
      region: ap-southeast-2     # Use your AWS region
      access_key_id: YOUR_ACCESS_KEY
      secret_access_key: YOUR_SECRET_KEY
      insecure: false            # Set to true if using non-HTTPS S3-compatible storage (e.g., MinIO in dev)

blocks_storage:
  backend: s3
  s3:
    bucket_name: your-mimir-bucket
    endpoint: s3.amazonaws.com
    region: ap-southeast-2
    access_key_id: YOUR_ACCESS_KEY
    secret_access_key: YOUR_SECRET_KEY
    insecure: false

ingester:
  ring:
    replication_factor: 1
